/// Static curated list of ~200 common cooking ingredient names.
///
/// Used for local-first search matching in [IngredientSearch] provider.
/// Search matches this list first (instant, no API call); the OpenFoodFacts
/// API is the fallback for uncommon items not found here.
///
/// Organized alphabetically, covering all 12 ingredient categories:
/// Produce, Dairy, Meat, Seafood, Grains, Legumes, Spices, Condiments,
/// Oils, Beverages, Baking, Nuts & Seeds.
const List<String> commonIngredients = [
  // A
  'All-Purpose Flour',
  'Almond',
  'Almond Milk',
  'Apple',
  'Apple Cider Vinegar',
  'Apricot',
  'Asparagus',
  'Avocado',
  // B
  'Bacon',
  'Baking Powder',
  'Baking Soda',
  'Banana',
  'Basil',
  'Bay Leaves',
  'Bell Pepper',
  'Black Bean',
  'Black Pepper',
  'Blueberry',
  'Bread',
  'Broccoli',
  'Brown Rice',
  'Brown Sugar',
  'Butter',
  'Buttermilk',
  // C
  'Cabbage',
  'Canola Oil',
  'Carrot',
  'Cashew',
  'Cauliflower',
  'Cayenne Pepper',
  'Celery',
  'Cheddar Cheese',
  'Chicken Breast',
  'Chicken Thigh',
  'Chickpea',
  'Chili Flakes',
  'Chili Powder',
  'Chives',
  'Chocolate Chips',
  'Cilantro',
  'Cinnamon',
  'Clove',
  'Cocoa Powder',
  'Coconut Milk',
  'Coconut Oil',
  'Cod',
  'Coffee',
  'Condensed Milk',
  'Corn',
  'Cornstarch',
  'Cream',
  'Cream Cheese',
  'Cucumber',
  'Cumin',
  // D
  'Dill',
  'Dried Cranberry',
  // E
  'Egg',
  'Eggplant',
  // F
  'Feta Cheese',
  'Flaxseed',
  // G
  'Garlic',
  'Garlic Powder',
  'Ginger',
  'Gouda Cheese',
  'Grape',
  'Greek Yogurt',
  'Green Bean',
  'Green Onion',
  'Ground Beef',
  'Ground Pork',
  'Ground Turkey',
  // H
  'Ham',
  'Hemp Seed',
  'Honey',
  'Hot Sauce',
  // I
  'Italian Seasoning',
  // J
  'Jalapeño',
  // K
  'Kale',
  'Ketchup',
  'Kidney Bean',
  // L
  'Lamb',
  'Leek',
  'Lemon',
  'Lemon Juice',
  'Lentil',
  'Lettuce',
  'Lime',
  'Lime Juice',
  // M
  'Maple Syrup',
  'Mayonnaise',
  'Milk',
  'Mozzarella Cheese',
  'Mushroom',
  'Mustard',
  'Mustard Seeds',
  // N
  'Navy Bean',
  'Nutmeg',
  // O
  'Oat',
  'Oat Milk',
  'Olive',
  'Olive Oil',
  'Onion',
  'Onion Powder',
  'Orange',
  'Orange Juice',
  'Oregano',
  // P
  'Paprika',
  'Parmesan Cheese',
  'Parsley',
  'Pasta',
  'Peach',
  'Peanut',
  'Peanut Butter',
  'Pear',
  'Peas',
  'Pecan',
  'Pineapple',
  'Pistachio',
  'Pork Chop',
  'Pork Loin',
  'Potato',
  'Pumpkin Seeds',
  // Q
  'Quinoa',
  // R
  'Raspberry',
  'Red Onion',
  'Red Pepper Flakes',
  'Red Wine Vinegar',
  'Rice',
  'Rice Vinegar',
  'Ricotta Cheese',
  'Rosemary',
  // S
  'Salmon',
  'Salt',
  'Sesame Oil',
  'Sesame Seeds',
  'Shrimp',
  'Smoked Paprika',
  'Sour Cream',
  'Soy Milk',
  'Soy Sauce',
  'Spinach',
  'Split Pea',
  'Sriracha',
  'Steak',
  'Strawberry',
  'Sugar',
  'Sunflower Oil',
  'Sunflower Seeds',
  'Sweet Potato',
  'Swiss Cheese',
  // T
  'Tahini',
  'Tamari',
  'Tea',
  'Thyme',
  'Tilapia',
  'Tofu',
  'Tomato',
  'Tomato Paste',
  'Tomato Sauce',
  'Tortilla',
  'Tuna',
  'Turmeric',
  // V
  'Vanilla Extract',
  'Vegetable Broth',
  'Vegetable Oil',
  'Venison',
  // W
  'Walnut',
  'Water',
  'White Beans',
  'White Rice',
  'White Sugar',
  'White Wine Vinegar',
  'Whole Wheat Flour',
  'Worcestershire Sauce',
  // Y
  'Yeast',
  'Yellow Onion',
  'Yogurt',
  // Z
  'Zucchini',
];
