// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file is generated by build_runner + drift_dev.
// Run: dart run build_runner build --delete-conflicting-outputs
//
// This placeholder exists to satisfy the `part 'app_database.g.dart';`
// directive in app_database.dart. The actual generated code is produced by
// running `dart run build_runner build` with the Flutter SDK installed.
//
// The CI pipeline (meal_mate/.github/workflows/flutter.yml) runs this command
// automatically on every push.
//
// Generated content will include:
//   - _$AppDatabase mixin with typed table accessors
//   - Ingredient, Recipe, MealPlanSlot, ShoppingListItem data classes
//   - IngredientsCompanion, RecipesCompanion, MealPlanSlotsCompanion,
//     ShoppingListItemsCompanion insert/update companion classes
//   - $IngredientsTable, $RecipesTable, $MealPlanSlotsTable,
//     $ShoppingListItemsTable typed query wrappers

part of 'app_database.dart';
